language: java

jdk:
  - openjdk11

sudo: false # faster builds

script: "./mvnw clean compile -DskipTests=true -Dmaven.javadoc.skip=true -B -V"

notifications:
  email:
    recipients:
      - claudio@claudioaltamura.de
    on_success: always # default: change
on_failure: always # default: always